language: cpp
branches:
    only:
        - master
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode8.3
cache:
    ccache: true
install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ethereum/ethereum; sudo apt-get update; sudo apt-get install -y --no-install-recommends --allow-unauthenticated libjson-rpc-cpp-dev libjsoncpp-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew install libjson-rpc-cpp jsoncpp; fi
script:
    - cmake -DETHASHCUDA=Off -DETHSTRATUM=On -DETHASHCL=On -H. -Bbuild
    - cmake --build build
    - build/ethminer/ethminer --list-devices -G